language: node_js
node_js:
    - "8"
install:
    - npm install -g npm@latest
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install
script:
    - npm run build
    - npm run start